version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      github_actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      pip_dependencies:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/terraform/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      terraform_modules:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    target-branch: v1.4
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    labels:
      - v1.4

  - package-ecosystem: "pip"
    target-branch: v1.4
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    labels:
      - v1.4

  - package-ecosystem: "terraform"
    target-branch: v1.4
    directory: "/terraform/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    labels:
      - v1.4
