name: Release 1.4 CI

on:
  pull_request:
    branches:
      - v1.4
  push:

jobs:
  codeql:
    name: CodeQL Analysis
    uses: canonical/sdcore-github-workflows/.github/workflows/codeql-analysis.yml@v0.0.1
    with:
      branch-name: ${{ github.ref }}

  check-libraries:
    uses: canonical/sdcore-github-workflows/.github/workflows/check-libraries.yaml@v0.0.1
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@v0.0.1
    with:
      branch-name: ${{ github.ref }}

  terraform-check:
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v0.0.1
    with:
      branch-name: ${{ github.ref }}


  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@v0.0.1
    with:
      branch-name: ${{ github.ref }}

  unit-tests-with-coverage:
    uses: canonical/sdcore-github-workflows/.github/workflows/unit-test.yaml@v0.0.1
    with:
      branch-name: ${{ github.ref }}

  integration-test:
    uses: canonical/sdcore-github-workflows/.github/workflows/integration-test.yaml@v0.0.1
    with:
      branch-name: ${{ github.ref }}
      charm-file-name: "sdcore-smf-k8s_ubuntu-22.04-amd64.charm"

  publish-charm:
    name: Publish Charm
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ github.ref_name == 'v1.4' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v0.0.1
    with:
      branch-name: ${{ github.ref_name }}
      charm-file-name: "sdcore-smf-k8s_ubuntu-22.04-amd64.charm"
      track-name: 1.4
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  publish-charm-on-push:
    name: Publish Developer Charm To Branch
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ (github.ref_name != 'v1.4') && (github.event_name == 'push') }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v0.0.1
    with:
      branch-name: ${{ github.ref_name }}
      charm-file-name: "sdcore-smf-k8s_ubuntu-22.04-amd64.charm"
      track-name: 1.4
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

