name: main-branch

on:
  push:

jobs:
  lint-report:
    name: Lint report
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e lint

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e static

  unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e unit

  integration-test:
    name: Integration tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.12/stable
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
      - name: Run integration tests
        run: tox -e integration
      - name: Archive Tested Charm
        uses: actions/upload-artifact@v3
        if: ${{ github.ref_name == 'main' }}
        with:
          name: tested-charm
          path: .tox/**/sdcore-smf_ubuntu-22.04-amd64.charm
          retention-days: 5
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz

  publish-charm:
    name: Publish Charm
    needs: integration-test
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Fetch Tested Charm
        uses: actions/download-artifact@v3
        with:
          name: tested-charm
      - name: Move charm in current directory
        run: find ./ -name sdcore-smf_ubuntu-22.04-amd64.charm -exec mv -t ./ {} \;
      - name: Select Charmhub channel
        uses: canonical/charming-actions/channel@2.2.5
        id: channel
      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.2.5
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
