name: Release 1.5 CI

on:
  pull_request:
    branches:
      - v1.5
  push:

jobs:
  codeql:
    name: CodeQL Analysis
    uses: canonical/sdcore-github-workflows/.github/workflows/codeql-analysis.yml@v2.2.0

  check-libraries:
    uses: canonical/sdcore-github-workflows/.github/workflows/check-libraries.yaml@v2.2.0
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@v2.2.0

  terraform-check:
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v2.2.0

  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@v2.2.0

  unit-tests-with-coverage:
    uses: canonical/sdcore-github-workflows/.github/workflows/unit-test.yaml@v2.2.0

  build:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    uses: canonical/sdcore-github-workflows/.github/workflows/build.yaml@v2.2.0
    secrets: inherit

  integration-test:
    needs:
      - build
    uses: canonical/sdcore-github-workflows/.github/workflows/integration-test.yaml@v2.2.0

  publish-charm:
    name: Publish Charm
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ github.ref_name == 'v1.5' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v2.2.0
    with:
      track-name: 1.5
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
