name: Main branch CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "20 7 * * 0"

jobs:
  codeql:
    name: CodeQL Analysis
    uses: canonical/sdcore-github-workflows/.github/workflows/codeql-analysis.yml@v2.3.2

  check-libraries:
    uses: canonical/sdcore-github-workflows/.github/workflows/check-libraries.yaml@v2.3.2
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  lint-report:
    uses: canonical/sdcore-github-workflows/.github/workflows/lint-report.yaml@v2.3.2

  terraform-check:
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v2.3.2

  static-analysis:
    uses: canonical/sdcore-github-workflows/.github/workflows/static-analysis.yaml@v2.3.2

  unit-tests-with-coverage:
    uses: canonical/sdcore-github-workflows/.github/workflows/unit-test.yaml@v2.3.2

  build:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    uses: canonical/sdcore-github-workflows/.github/workflows/build.yaml@v2.3.2
    secrets: inherit

  integration-test:
    needs:
      - build
    uses: canonical/sdcore-github-workflows/.github/workflows/integration-test.yaml@v2.3.2

  publish-charm:
    name: Publish Charm
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ github.ref_name == 'main' }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v2.3.2
    with:
      track-name: 1.6
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

  publish-charm-on-push:
    name: Publish Developer Charm To Branch
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ (github.ref_name != 'main') && (github.event_name == 'push') }}
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-charm.yaml@v2.3.2
    with:
      branch-name: ${{ github.ref_name }}
      track-name: 1.6
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}

