name: Static analysis

on:
  workflow_call:

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e static
